### ISSUE TITLE
量化

### ISSUE THREAD

**Issue by chen990627** [yyccR/yolov5-tflite-android#1]
请问大佬有没有量化的源码呀

**Comment by yyccR** [comment]
tflite不是开源的吗？

**Comment by chen990627** [comment]
> tflite不是开源的吗？

我是想部署自己训练的模型来着

**Comment by yyccR** [comment]
视频里面或者PPT里面有讲怎么 量化导出自己的模型，怎么部署到Android。

**Comment by chen990627** [comment]
> 视频里面或者PPT里面有讲怎么 量化导出自己的模型，怎么部署到Android。

好的，谢谢大佬。
