### ISSUE TITLE
showing random boxes on custom model

### ISSUE THREAD

**Issue by sabsabrin** [yyccR/yolov5-tflite-android#4]
I have trained a custom trained model with input 416x416 and seven classes; it shows random boxes that fill the image.. please help me resolve this. I have tested it on another custom-trained model with only 2 classes, and it worked fine.

**Comment by yyccR** [comment]
1. have u update the model input/output size? [ref](https://github.com/yyccR/yolov5-tflite-android/blob/c0d0940c66f70c4dd8e9e321c8dbd4d64c2638f9/app/src/main/java/com/example/yolov5tfliteandroid/detector/Yolov5TFLiteDetector.java#L48-L49)
```
private final Size INPNUT_SIZE = new Size(320, 320);
private final int[] OUTPUT_SIZE = new int[]{1, 6300, 85};
```
2. have u update the asserts/coco_label.txt? [ref](https://github.com/yyccR/yolov5-tflite-android/blob/master/app/src/main/assets/coco_label.txt)

**Comment by sabsabrin** [comment]
@yyccR Yes, I have changed those values into:

`private final Size INPNUT_SIZE = new Size(416,416); `
`private final int[] OUTPUT_SIZE = new int[]{1, 10647, 12};`

and changed the text file and tflite model.

but output is like this:

![Screenshot_20240312-174504 1](https://github.com/yyccR/yolov5-tflite-android/assets/33210474/b73bfc65-e77d-4bb4-adf7-ef740b28a14c)

**Comment by sabsabrin** [comment]
I have another trained model with only 2 classes with the same input size and output shape (1, 10647, 7) and working just fine, as shown below:

![Screenshot_20240312-181328 1](https://github.com/yyccR/yolov5-tflite-android/assets/33210474/b3dd146f-788c-4bb2-b2f7-cd138eb89145)

**Comment by yyccR** [comment]
@sabsabrin 
which version of yolov5 and which version of tflite? and how do u export the yolov5 tflite model? show me your code?

**Comment by yyccR** [comment]
> I have another trained model with only 2 classes with the same input size and output shape (1, 10647, 7) and working just fine, as shown below:

Are you training this 2-class model using the same methods and versions as the 7-class model？

**Comment by sabsabrin** [comment]
> > I have another trained model with only 2 classes with the same input size and output shape (1, 10647, 7) and working just fine, as shown below:
> 
> Are you training this 2-class model using the same methods and versions as the 7-class model？

@yyccR yes, sir, I have trained the 2-class model using the same method and version as the 7-class model. I'm using yolov5s. This is how I export it to tflite:

`!python yolov5/export.py --weights yolov5/runs/train/exp/weights/best.pt --include tflite --img 416`

**Comment by yyccR** [comment]
> @yyccR Yes, I have changed those values into:
> 
> `private final Size INPNUT_SIZE = new Size(416,416); ` `private final int[] OUTPUT_SIZE = new int[]{1, 10647, 12};`
> 
> and changed the text file and tflite model.
> 
> but output is like this:
> 
> ![Screenshot_20240312-174504 1](https://private-user-images.githubusercontent.com/33210474/312026996-b73bfc65-e77d-4bb4-adf7-ef740b28a14c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTM1NTksIm5iZiI6MTcxMDI5MzI1OSwicGF0aCI6Ii8zMzIxMDQ3NC8zMTIwMjY5OTYtYjczYmZjNjUtZTc3ZC00YmI0LWFkZjctZWY3NDBiMjhhMTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAxMjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MzI2MzVlYzVkNjY1M2EyOGE3ZmViM2U3Y2U3MWQ1NTVkMTQxZjg2MGZhMGMzMGU0NGMyYmI4NWE3OTAyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.deljwJLJVcLqQo6ICuKlFpLdPcKJIL3f6BrHVbiphp8)

I think u can try to increase the nms threshold. [ref](https://github.com/yyccR/yolov5-tflite-android/blob/master/app/src/main/java/com/example/yolov5tfliteandroid/detector/Yolov5TFLiteDetector.java#L51)
```
private final float DETECT_THRESHOLD = 0.25f;
```
When the model is trained more fully and the accuracy is higher, the nms threshold can be increased appropriately.

**Comment by sabsabrin** [comment]
@yyccR I have resolved this issue now; the problem is not with the code but with the badly trained model, I replaced it with a high mAP model, and it is working well now. 

Of all the repos of yolov5 to tflite Android that I've tested, yours was the easiest to be ported to new projects. I hope you could also create tflite for other higher yolo versions.

Thank you very much for the help. More power.

**Comment by yyccR** [comment]
@sabsabrin  thx for your suggestion. Currently I am also writing an AI lightweight deployment application that supports various infer frameworks. It will be open source in the future.

<img width="662" alt="image" src="https://github.com/yyccR/yolov5-tflite-android/assets/14156500/466698f1-71e1-4120-8b13-3c3c85422b12">
